### ISSUE TITLE
Testbed structure and options needed

### ISSUE THREAD

**Issue by pwoconnor** [hpreston/netdevops_demos#5]
Since Genie and PyATS are closed source, we do not really have a way to look for what kind of options there are to include in testbed files. For instance, I noticed that with GenieCLI, anytime you make a connection with learn. Genie makes configuration changes to line console (ios and iosxr), and line default (iosxr). Not sure about anybody else, but I know I do not want configuration changes being made to any device without me knowing about it. 

Also I saw that you have a mock commands section in your testbed file. How would we go about getting the correct info and syntax for that?

Any plans on publishing this type of information concerning the testbed files?

I realize this is not he GenieCLI repo and these questions probably belong in that repo. I am unsure what that repo acutally is. I did find the genielibs repo and have opened a couple issues about the points above there. I figured no harm in looking everywhere I can for info on those testbed files.

**Comment by hpreston** [comment]
@pwoconnor thanks for opening the issue.. and great points. 

My repo here is mainly used for sharing code for demo's I give, and providing some examples.  They are all point in time examples, and I try to be as thorough as possible in explanations, but I don't try to replace the "official docs".  

Here is a link to the the pyATS testbed official docs and info, hopefully you can find what you are looking for there - https://pubhub.devnetcloud.com/media/pyats/docs/topology/index.html 

And the details on the "mock" devices are available here - https://pubhub.devnetcloud.com/media/pyats-packages/docs/unicon/playback/index.html

**Comment by pwoconnor** [comment]
Thanks for the feedback! I check out the docs and do some learning!
